language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty

branches:
  only:
   - master

before_script:
  - cd src

install:
 - sudo apt-get install -y python3-pip
 - sudo pip3 install pexpect

script:
 - cd src
 - make clean && make build ARCH=x86-64
 - python3 test.py
 - mv scoutfish scoutfish_x64
 - make clean && make build ARCH=x86-32 EXE=scoutfish_x32
 - ls -l

deploy:
  provider: releases
  api_key:
    secure:
  prerelease: true
  file_glob: true
  file:
    - $BASEEXE-*
  skip_cleanup: true
  on:
    tags: true
    repo: gbtami/scoutfish
    branch: master
